### ISSUE TITLE
NF3: Ein Nutzer kann sein Profil löschen

### ISSUE THREAD

**Issue by Der-Alex** [oforge/oforge-core#5]
### Beschreibung: 
Ein registrierter Nutzer kann sein Profil löschen. Nach der Löschung werden alle Inserate deaktiviert sowie der Absender-Name von Kommentaren und Nachrichten mit „Gelöschter Nutzer“ überschrieben.

### Modul:
UserManagement
#### Abhängigkeit zu
Auth

### Abhängigkeiten:
- [ ] #7 Nutzerprofil pflegen

**Comment by mys3lf** [comment]
Der Prozess wurde geändert. Der Nutzer muss eine Supportanfrage zur Löschung stellen. Das Ticket ist daher fertig.
