### ISSUE TITLE
Erstelle einen UserController für das Admin Backend

### ISSUE THREAD

**Issue by Der-Alex** [oforge/oforge-core#79]
### Beschreibung:
Als Administrator kann ich mein eigenes Profil anpassen oder Profile in der Benutzerverwaltung anlegen, bearbeiten oder löschen.

### Methoden: 
- [x] indexAction (Einen oder mehrere Nutzer anzeigen)
- [x] updateAction 
- [x] deactivateAction
- [x] deleteAction

#### Methoden für die Verwaltung der Admin Backend Nutzer
- [x] adminIndexAction
- [x] adminUpdateAction
- [ ] adminDeleteAction

### Akzeptanzkriterien: 
- [ ] Controller ist über eine Route erreichbar
- [ ] Controller ist dokumentiert

**Comment by mys3lf** [comment]
Scheint fertig. Bitte kontrollieren und schließen
