### ISSUE TITLE
Erstelle einen BackendLoginService

### ISSUE THREAD

**Issue by Der-Alex** [oforge/oforge-core#87]
### Beschreibung
Als Entwickler steht mir ein BackendLoginService zur Verfügung, mit dem die Verarbeitung und Validierung der Benutzerdaten Für das Admin Backend durchgeführt werden kann.

### Methoden
- [x] login (Anmeldung im Portal durchführen)
- [x] comparePasswords (Passwort validieren)

### Akzeptanzkriterien
- [x] Wenn die Daten valide sind, wird eine Sitzung (muss nicht Session sein) erzeugt
- [x] Service ist dokumentiert
- [x] Alle Service Funktionen sind positiv getestet

**Comment by Der-Alex** [comment]
removed logout. This will be part of the controller #88

**Comment by mys3lf** [comment]
Das scheint mir fertig zu sein. Bitte kontrollieren und schließen
