### ISSUE TITLE
Erstelle einen Backend Login Controller

### ISSUE THREAD

**Issue by Der-Alex** [oforge/oforge-core#88]
### Beschreibung
Als Entwickler steht mir ein LoginController für das Admin Backend zur Verfügung, mit dem ich die An- und Abmeldung von Benutzern steuern kann.

### Methoden
- [x] indexAction (Anzeige des Login Formulars)
- [x] loginAction (Login Funktion ausführen)
- [x] logoutAction (Logout Funktion ausführen)

### Akzeptanzkriterien
- [ ] Benutzer kann sich anmelden
- [ ] Benutzer kann sich abmelden
- [ ] Bei fehlerhaften Benutzerdaten werden passende Fehlermeldungen generiert
- [ ] Im dazugehörigen Modul muss eine Route für Login und Logout vorhanden und aufrufbar sein, die den Controller ansteuert
- [ ] Controller ist dokumentiert

**Comment by mys3lf** [comment]
Scheint fertig. Bitte kontrollieren und schließen
